2020-03-08 11:11:43,691 ERROR: Exception on /user/1 [GET] [in c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\main\routes.py", line 55, in user
    events=events)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\templates\base.html", line 44, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\templates\user.html", line 34, in block "app_content"
    {{form.hidden_tag() }}
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-03-08 11:16:48,481 INFO: ffgt86 startup [in C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\__init__.py:56]
2020-03-08 11:17:59,379 INFO: ffgt86 startup [in C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\__init__.py:56]
2020-03-08 11:18:24,065 INFO: ffgt86 startup [in C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\__init__.py:56]
2020-03-08 11:18:47,295 ERROR: Exception on /user/1 [GET] [in c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\main\routes.py", line 55, in user
    events=events)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\templates\base.html", line 44, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\domwh\PycharmProjects\Recommender-Systems-Coursework\app\templates\user.html", line 34, in block "app_content"
    {{form.hidden_tag() }}
  File "c:\users\domwh\pycharmprojects\recommender-systems-coursework\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
